# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

#target 'lobby-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lobby-desktop

#end

target 'lobby-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lobby-mobile

  pod 'SSZipArchive'
  pod 'CocoaHTTPServer', '~> 2.3'
  pod 'libOpenInstallSDK'

end
